name: Compilar Flet APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Configurar Java JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Compilar APK usando Acción Oficial de Flet
      id: build
      uses: flet-dev/flet-build-action@v1
      with:
        target: apk
        runner-python-version: "3.11"
        bundled-python-version: "3.11"

    - name: Subir APK generado como resultado descargable
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: ${{ steps.build.outputs.archive-path }}
        if-no-files-found: error
